// module.exports = {
//     dsa: [
//         "DFSOnBST",
//         "LRU",
//         "LinearSearchList",
//         "BinarySearchList",
//         "TwoCrystalBalls",
//         "BubbleSort",
//         "SinglyLinkedList",
//         "DoublyLinkedList",
//         "Queue",
//         "Stack",
//         "ArrayList",
//         "MazeSolver",
//         "QuickSort",
//         "BTPreOrder",
//         "BTInOrder",
//         "BTPostOrder",
//         "BTBFS",
//         "CompareBinaryTrees",
//         "DFSOnBST",
//         "DFSGraphList",
//         "Trie",
//         "BFSGraphMatrix",
//         "Map",
//         "MinHeap",
//     ],
// }

module.exports = {
    dsa: [
        "InsertionSort",
        "MergeSort",
        "Queue",
        "Stack",
        "QuickSort",
        "DijkstraList",
        "PrimsList",
    ],
}
